name: 'Terraform'

  
on:
  workflow_dispatch:
    inputs:
      infra_env:
        description: 'Environment Name'
        required: true
        default: 'provide one (sandbox/nonprod/prod)'
      add_adgroup:
        description: 'Want to add ad group to local Admin'
        required: true
        default: 'provide one (yes/no)'
        

env:

  APP_ID: RITM031323

jobs:

  terraform:
    name: "terraform scan & Plan"
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
